/*
*	This file is auto-generated, do not edit manually.
*/

#pragma once

//Core.
#include <Core/Core/CatalystCore.h>

//Rendering.
#include <Rendering/ShaderData/Vulkan/AboveOceanFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/AntiAliasingFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/BelowOceanFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/BloomHorizontalFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/BloomVerticalFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/BoxBlurFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/DebugAxisAlignedBoundingBoxFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/DebugAxisAlignedBoundingBoxVertexShader.h>
#include <Rendering/ShaderData/Vulkan/DebugScreenBoxFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/DebugScreenBoxVertexShader.h>
#include <Rendering/ShaderData/Vulkan/DepthOfFieldFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/DirectionalPhysicalShadowVertexShader.h>
#include <Rendering/ShaderData/Vulkan/DirectionalShadowFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/DirectionalSolidVegetationShadowFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/DirectionalSolidVegetationShadowVertexShader.h>
#include <Rendering/ShaderData/Vulkan/DirectionalTerrainShadowVertexShader.h>
#include <Rendering/ShaderData/Vulkan/DirectionalTreeVegetationTrunkVertexShader.h>
#include <Rendering/ShaderData/Vulkan/GaussianBlurFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailDebrisVegetationFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailDebrisVegetationVertexShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailGrassVegetationColorFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailGrassVegetationColorVertexShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailGrassVegetationDepthFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailGrassVegetationDepthVertexShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailSolidVegetationFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailSolidVegetationVertexShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationCrownColorFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationCrownColorVertexShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationCrownDepthFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationCrownDepthVertexShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationImpostorColorFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationImpostorColorGeometryShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationImpostorColorVertexShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationImpostorDepthFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationImpostorDepthGeometryShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationImpostorDepthVertexShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationTrunkFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/HighDetailTreeVegetationTrunkVertexShader.h>
#include <Rendering/ShaderData/Vulkan/LightingFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailDebrisVegetationFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailDebrisVegetationVertexShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailGrassVegetationColorFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailGrassVegetationColorVertexShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailGrassVegetationDepthFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailGrassVegetationDepthVertexShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailSolidVegetationFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailSolidVegetationVertexShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationCrownColorFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationCrownColorVertexShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationCrownDepthFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationCrownDepthVertexShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationImpostorColorFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationImpostorColorGeometryShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationImpostorColorVertexShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationImpostorDepthFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationImpostorDepthGeometryShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationImpostorDepthVertexShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationTrunkFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/LowDetailTreeVegetationTrunkVertexShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailDebrisVegetationFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailDebrisVegetationVertexShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailGrassVegetationColorFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailGrassVegetationColorVertexShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailGrassVegetationDepthFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailGrassVegetationDepthVertexShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailSolidVegetationFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailSolidVegetationVertexShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailTreeVegetationCrownColorFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailTreeVegetationCrownColorVertexShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailTreeVegetationCrownDepthFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailTreeVegetationCrownDepthVertexShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailTreeVegetationTrunkFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/MediumDetailTreeVegetationTrunkVertexShader.h>
#include <Rendering/ShaderData/Vulkan/OutlineFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/ParticleSystemFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/ParticleSystemGeometryShader.h>
#include <Rendering/ShaderData/Vulkan/ParticleSystemVertexShader.h>
#include <Rendering/ShaderData/Vulkan/PhysicalFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/PhysicalVertexShader.h>
#include <Rendering/ShaderData/Vulkan/ReSampleFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/ScreenSpaceAmbientOcclusionFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/ShadowMapFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/SkyFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/TerrainColorFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/TerrainDepthFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/TerrainVertexShader.h>
#include <Rendering/ShaderData/Vulkan/ToneMappingFragmentShader.h>
#include <Rendering/ShaderData/Vulkan/ViewportVertexShader.h>
#include <Rendering/ShaderData/Vulkan/VolumetricFogFragmentShader.h>
