#if !defined(CATALYST_SHADER_CONSTANTS)
#define CATALYST_SHADER_CONSTANTS

#if defined(CATALYST_SHADER_LANGUAGE_CXX)
	#include "CatalystShaderCore.h"
#endif

#if defined(CATALYST_SHADER_LANGUAGE_GLSL)
	#include "..\..\Include\Rendering\Native\Shader\CatalystShaderCore.h"
#endif

CATALYST_SHADER_NAMESPACE_BEGIN(CatalystShaderConstants)
	//General.
	CATALYST_SHADER_CONSTANT(uint, MAXIMUM_NUMBER_OF_GLOBAL_TEXTURES, 1024)
	CATALYST_SHADER_CONSTANT(uint, MAXIMUM_NUMBER_OF_GLOBAL_MATERIALS, 255)
	
	//Sky.
	CATALYST_SHADER_CONSTANT(uint, SKY_TEXTURE_BASE_RESOLUTION, 512)
	CATALYST_SHADER_CONSTANT(uint, NUMBER_OF_SKY_TEXTURES, 7)
CATALYST_SHADER_NAMESPACE_END()

#endif