#if !defined(CATALYST_SHADER_CONSTANTS)
#define CATALYST_SHADER_CONSTANTS

#if defined(CATALYST_SHADER_LANGUAGE_CXX)
	#include "CatalystShaderCore.h"
#endif

#if defined(CATALYST_SHADER_LANGUAGE_GLSL)
	#include "..\Include\Rendering\Native\Shader\CatalystShaderCore.h"
#endif

CATALYST_SHADER_NAMESPACE_BEGIN(CatalystShaderConstants)
	//Core.
	CATALYST_SHADER_CONSTANT(uint, MAXIMUM_NUMBER_OF_GLOBAL_TEXTURES, 4096)
	CATALYST_SHADER_CONSTANT(uint, MAXIMUM_NUMBER_OF_GLOBAL_MATERIALS, 512)
	CATALYST_SHADER_CONSTANT(uint, NUMBER_OF_BLUE_NOISE_TEXTURES, 32)
	CATALYST_SHADER_CONSTANT(uint, BLUE_NOISE_TEXTURE_RESOLUTION, 32)

	//Render target indices.
	CATALYST_SHADER_CONSTANT(uint, SCENE_FEATURES_2_HALF_RENDER_TARGET_INDEX,							0)
	CATALYST_SHADER_CONSTANT(uint, SCENE_FEATURES_3_HALF_RENDER_TARGET_INDEX,							1)
	CATALYST_SHADER_CONSTANT(uint, SCENE_FEATURES_4_HALF_RENDER_TARGET_INDEX,							2)
	CATALYST_SHADER_CONSTANT(uint, SCENE_RENDER_TARGET_INDEX,											3)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_UINT8_RENDER_TARGET_INDEX,							4)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_1_RENDER_TARGET_INDEX,						5)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_2_RENDER_TARGET_INDEX,						6)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_HALF_1_RENDER_TARGET_INDEX,				7)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_HALF_2_RENDER_TARGET_INDEX,				8)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_QUARTER_RENDER_TARGET_INDEX,				9)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_EIGHTH_RENDER_TARGET_INDEX,				10)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_SIXTEENTH_RENDER_TARGET_INDEX,				11)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_THIRTYSECOND_RENDER_TARGET_INDEX,			12)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_SIXTYFOURTH_RENDER_TARGET_INDEX,			13)
	CATALYST_SHADER_CONSTANT(uint, INTERMEDIATE_RGBA_FLOAT32_HUNDREDTWENTYEIGHTH_RENDER_TARGET_INDEX,	14)
	CATALYST_SHADER_CONSTANT(uint, NUMBER_OF_RENDER_TARGETS,											15)

	//Material.
	CATALYST_SHADER_CONSTANT(uint, MATERIAL_PROPERTY_TYPE_MASKED, 1 << 0)
	CATALYST_SHADER_CONSTANT(uint, MATERIAL_PROPERTY_TYPE_OPAQUE, 1 << 1)
	CATALYST_SHADER_CONSTANT(uint, MATERIAL_PROPERTY_TYPE_TRANSLUCENT, 1 << 2)
	CATALYST_SHADER_CONSTANT(uint, MATERIAL_PROPERTY_ALBEDO_THICKNESS_TEXTURE, 1 << 3)
	CATALYST_SHADER_CONSTANT(uint, MATERIAL_PROPERTY_NORMAL_MAP_DISPLACEMENT_TEXTURE, 1 << 4)
	CATALYST_SHADER_CONSTANT(uint, MATERIAL_PROPERTY_MATERIAL_PROPERTIES_TEXTURE, 1 << 5)
	CATALYST_SHADER_CONSTANT(uint, MATERIAL_PROPERTY_OPACITY_TEXTURE, 1 << 6)

	//Ambient occlusion.
	CATALYST_SHADER_CONSTANT(float, AMBIENT_OCCLUSION_RADIUS, 2.0f)

	//Lighting.
	CATALYST_SHADER_CONSTANT(uint, LIGHT_PROPERTY_SURFACE_SHADOW_CASTING_BIT, 1)
	CATALYST_SHADER_CONSTANT(uint, LIGHT_PROPERTY_VOLUMETRIC_BIT, 2)
	CATALYST_SHADER_CONSTANT(uint, LIGHT_PROPERTY_VOLUMETRIC_SHADOW_CASTING_BIT, 4)
	CATALYST_SHADER_CONSTANT(vec3, VOLUMETRIC_LIGHTING_BASE_COLOR, vec3(0.8f, 0.9f, 1.0f))
	CATALYST_SHADER_CONSTANT(float, VOLUMETRIC_LIGHTING_DENSITY_MULTIPLIER, 0.125f)

CATALYST_SHADER_NAMESPACE_END()

#endif