#if !defined(CATALYST_MODEL_CORE)
#define CATALYST_MODEL_CORE

//Constants.
#define MODEL_FLAG_INCLUDE_IN_SHADOW_CASCADE_1 	(BIT(0))
#define MODEL_FLAG_INCLUDE_IN_SHADOW_CASCADE_2 	(BIT(1))
#define MODEL_FLAG_INCLUDE_IN_SHADOW_CASCADE_3 	(BIT(2))
#define MODEL_FLAG_INCLUDE_IN_SHADOW_CASCADE_4 	(BIT(3))
#define MODEL_FLAG_IS_VEGETATION 				(BIT(4))

#endif