ResourceCreator.exe EnvironmentMaterial Intermediate/Materials/DefaultEnvironmentMaterial DefaultEnvironmentMaterial Raw/Textures/MalibuEnvironment.hdr 2048 32
ResourceCreator.exe ParticleMaterial Intermediate/Materials/Cloud1Material Cloud1Material 5 Raw/Textures/Particles/Cloud1.png
ResourceCreator.exe ParticleMaterial Intermediate/Materials/EnergyParticleMaterial EnergyParticleMaterial 5 Raw/Textures/Particles/Energy.png
ResourceCreator.exe ParticleMaterial Intermediate/Materials/Fog1Material Fog1Material 5 Raw/Textures/Particles/Fog1.png
ResourceCreator.exe ParticleMaterial Intermediate/Materials/ParticleMaterial ParticleMaterial 5 Raw/Textures/Particles/Particle.png
ResourceCreator.exe PhysicalMaterial Intermediate/Materials/StoneMaterial StoneMaterial 5 Raw/Textures/StoneAlbedo.png Raw/Textures/StoneNormalMap.png Raw/Textures/StoneRoughness.png None Raw/Textures/StoneAmbientOcclusion.png Raw/Textures/StoneDisplacement.png
ResourceCreator.exe PhysicalMaterial Intermediate/Materials/TreeStompMaterial TreeStompMaterial 5 Raw/Textures/TreeStompAlbedo.jpg Raw/Textures/TreeStompNormalMap.jpg None None None None
ResourceCreator.exe PhysicalModel Intermediate/Models/StoneModel StoneModel Raw/Models/Stone.obj
ResourceCreator.exe PhysicalModel Intermediate/Models/TreeStompModel TreeStompModel Raw/Models/TreeStomp.obj
ResourceCreator.exe SoundBank Intermediate/SoundBanks/MasterSoundBank MasterSoundBank Raw/SoundBanks/MasterBank.bank
ResourceCreator.exe TerrainMaterial Intermediate/Materials/DefaultTerrainMaterial DefaultTerrainMaterial 7 Raw/Textures/Sand1Albedo.png Raw/Textures/Sand1NormalMap.png Raw/Textures/Sand1Roughness.png None Raw/Textures/Sand1AmbientOcclusion.png Raw/Textures/Sand1Displacement.png Raw/Textures/Grass1Albedo.png Raw/Textures/Grass1NormalMap.png Raw/Textures/Grass1Roughness.png None Raw/Textures/Grass1AmbientOcclusion.png Raw/Textures/Grass1Displacement.png Raw/Textures/Stone5Albedo.png Raw/Textures/Stone5NormalMap.png Raw/Textures/Stone5Roughness.png None Raw/Textures/Stone5AmbientOcclusion.png Raw/Textures/Stone5Displacement.png Raw/Textures/Stone1Albedo.png Raw/Textures/Stone1NormalMap.png Raw/Textures/Stone1Roughness.png None Raw/Textures/Stone1AmbientOcclusion.png Raw/Textures/Stone1Displacement.png Raw/Textures/Snow3Albedo.png Raw/Textures/Snow3NormalMap.png Raw/Textures/Snow3Roughness.png None Raw/Textures/Snow3AmbientOcclusion.png Raw/Textures/Snow3Displacement.png
ResourceCreator.exe VegetationMaterial Intermediate/Materials/DefaultVegetationMaterial DefaultVegetationMaterial 1 7 Raw/Textures/Vegetation/Mask.png Raw/Textures/Vegetation/Albedo.png Raw/Textures/Vegetation/NormalMap.png
ResourceCreator.exe WaterMaterial Intermediate/Materials/DefaultWaterMaterial DefaultWaterMaterial 5 Raw/Textures/WaterNormal.png

ResourceCreator.exe ResourceCollection Final/ClairvoyantResourceCollection Intermediate/Materials/DefaultEnvironmentMaterial.cr Intermediate/Materials/Cloud1Material.cr Intermediate/Materials/EnergyParticleMaterial.cr Intermediate/Materials/Fog1Material.cr Intermediate/Materials/ParticleMaterial.cr Intermediate/Materials/StoneMaterial.cr Intermediate/Materials/TreeStompMaterial.cr Intermediate/Models/StoneModel.cr Intermediate/Models/TreeStompModel.cr Intermediate/SoundBanks/MasterSoundBank.cr Intermediate/Materials/DefaultTerrainMaterial.cr Intermediate/Materials/DefaultVegetationMaterial.cr Intermediate/Materials/DefaultWaterMaterial.cr

pause